let data;const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];async function api(url,options={}){const r=await fetch(url,{credentials:'same-origin',cache:'no-store',...options});const j=await r.json().catch(()=>({}));if(r.status===401){location.replace('/admin/');throw new Error('Sessão expirada. Entre novamente.')}if(!r.ok)throw new Error(j.error||`Erro na operação (${r.status})`);return j}function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}function serviceIcon(s){return s.iconImage?`<img class="admin-icon-preview" src="${esc(s.iconImage)}" alt="">`:`<i class="bi ${esc(s.iconClass||'bi-briefcase')}"></i>`}const iconOptions=['bi-link-45deg','bi-globe2','bi-instagram','bi-facebook','bi-linkedin','bi-youtube','bi-tiktok','bi-twitter-x','bi-whatsapp','bi-telegram','bi-pinterest','bi-github','bi-behance','bi-dribbble','bi-briefcase','bi-images','bi-file-earmark-person','bi-envelope','bi-telephone','bi-geo-alt'];const socialPlatforms={Instagram:'bi-instagram',Facebook:'bi-facebook',LinkedIn:'bi-linkedin',YouTube:'bi-youtube',TikTok:'bi-tiktok',X:'bi-twitter-x',WhatsApp:'bi-whatsapp',Telegram:'bi-telegram',Pinterest:'bi-pinterest',GitHub:'bi-github',Behance:'bi-behance',Dribbble:'bi-dribbble',Website:'bi-globe2'};const statusLabel={pending:'Em análise',approved:'Aprovado',rejected:'Rejeitado',suspended:'Suspenso'};const verificationLabel={pending:'Em análise',approved:'Validada',rejected:'Rejeitada'};async function busyAction(btn,fn){if(btn?.disabled)return;if(btn)btn.disabled=true;try{return await fn()}finally{if(btn)btn.disabled=false}}
function ensureAdminDialog(){let d=$('#adminActionDialog');if(d)return d;d=document.createElement('dialog');d.id='adminActionDialog';d.className='admin-action-dialog';d.innerHTML=`<form method="dialog" class="admin-dialog-card"><button type="button" class="admin-dialog-x" data-dialog-cancel aria-label="Fechar"><i class="bi bi-x-lg"></i></button><span class="admin-dialog-icon"><i class="bi bi-chat-square-text"></i></span><h3 data-dialog-title></h3><p data-dialog-message></p><div data-dialog-field></div><div class="admin-dialog-actions"><button type="button" class="secondary" data-dialog-cancel>Cancelar</button><button type="button" data-dialog-confirm>Confirmar</button></div></form>`;document.body.appendChild(d);return d}
function uiDialog({title='Yuran Multicerviços',message='',mode='alert',defaultValue='',placeholder='',inputType='text',confirmText='Confirmar',danger=false,required=false,multiline=false}={}){return new Promise(resolve=>{const d=ensureAdminDialog(),titleEl=d.querySelector('[data-dialog-title]'),msg=d.querySelector('[data-dialog-message]'),field=d.querySelector('[data-dialog-field]'),confirmBtn=d.querySelector('[data-dialog-confirm]'),cancelBtns=d.querySelectorAll('[data-dialog-cancel]');titleEl.textContent=title;msg.textContent=message;field.innerHTML='';let input=null;if(mode==='prompt'){input=multiline?document.createElement('textarea'):document.createElement('input');if(!multiline)input.type=inputType;input.value=defaultValue||'';input.placeholder=placeholder||'';input.className='admin-dialog-input';if(multiline)input.rows=5;field.appendChild(input)}confirmBtn.textContent=mode==='alert'?'OK':confirmText;confirmBtn.classList.toggle('danger',danger);cancelBtns.forEach(b=>b.hidden=mode==='alert');let finished=false;const finish=value=>{if(finished)return;finished=true;d.close();resolve(value)};confirmBtn.onclick=()=>{if(input&&required&&!input.value.trim()){input.focus();input.classList.add('invalid');return}finish(mode==='prompt'?input.value:true)};cancelBtns.forEach(b=>b.onclick=()=>finish(mode==='prompt'?null:false));d.oncancel=e=>{e.preventDefault();finish(mode==='prompt'?null:false)};d.showModal();setTimeout(()=>input?.focus()||confirmBtn.focus(),30)})}
const uiAlert=(message,title='Informação')=>uiDialog({title,message,mode:'alert'});const uiConfirm=(message,{title='Confirmar ação',confirmText='Confirmar',danger=false}={})=>uiDialog({title,message,mode:'confirm',confirmText,danger});const uiPrompt=(message,{title='Informação necessária',defaultValue='',placeholder='',inputType='text',confirmText='Continuar',danger=false,required=false,multiline=true}={})=>uiDialog({title,message,mode:'prompt',defaultValue,placeholder,inputType,confirmText,danger,required,multiline});window.alert=(message)=>{uiAlert(String(message||''));};
const adminTabTitles={geral:'Visão geral',servicos:'Serviços',portfolio:'Portfólio',equipa:'Equipa',parceiros:'Parceiros',links:'Ligações',socials:'Redes sociais',moderacao:'Moderação',desempenho:'Desempenho',denuncias:'Denúncias',avaliacoes:'Avaliações',auditoria:'Auditoria',comunicacao:'Comunicação',seguranca:'Segurança'};
function applyAdminBrand(){const settings=data?.settings||{},logo=settings.headerLogoDark||settings.headerLogoLight||settings.headerLogo||settings.logo||'';const img=$('#adminBrandLogo'),fallback=$('#adminBrandFallback');if(img){if(logo){img.src=logo;img.hidden=false;if(fallback)fallback.hidden=true}else{img.hidden=true;if(fallback)fallback.hidden=false}}}
function setAdminTab(tab,{scroll=true}={}){const target=$(`#tab-${tab}`);if(!target)return;$$('#adminNav button[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));$$('.tab').forEach(t=>t.classList.toggle('active',t===target));const title=$('#adminCurrentTitle');if(title)title.textContent=adminTabTitles[tab]||'Painel';try{localStorage.setItem('yuran-admin-tab',tab)}catch{};if(tab==='moderacao')renderModeration();if(tab==='desempenho')renderAnalytics();if(tab==='denuncias')renderReports();if(tab==='avaliacoes')renderRatings();if(tab==='auditoria')renderAudit();if(tab==='comunicacao')renderCommunication();if(tab==='seguranca')renderSecurity();document.body.classList.remove('admin-menu-open');if(scroll)window.scrollTo({top:0,behavior:'smooth'})}
function setupAdminShell(){const sidebar=$('#adminSidebar'),collapse=$('#sidebarCollapse'),mobile=$('#mobileSidebarToggle');let collapsed=false;try{collapsed=localStorage.getItem('yuran-admin-sidebar-collapsed')==='1'}catch{};document.body.classList.toggle('admin-sidebar-collapsed',collapsed);if(collapse)collapse.onclick=()=>{const next=!document.body.classList.contains('admin-sidebar-collapsed');document.body.classList.toggle('admin-sidebar-collapsed',next);try{localStorage.setItem('yuran-admin-sidebar-collapsed',next?'1':'0')}catch{}};if(mobile)mobile.onclick=()=>document.body.classList.toggle('admin-menu-open');document.addEventListener('click',e=>{if(innerWidth>900||!document.body.classList.contains('admin-menu-open'))return;if(sidebar?.contains(e.target)||mobile?.contains(e.target))return;document.body.classList.remove('admin-menu-open')});$$('#adminNav button[data-tab]').forEach(btn=>btn.onclick=()=>setAdminTab(btn.dataset.tab));let saved='geral';try{saved=localStorage.getItem('yuran-admin-tab')||'geral'}catch{};setAdminTab(adminTabTitles[saved]?saved:'geral',{scroll:false});setupAdminPwa()}
let adminDeferredInstall=null;
function setupAdminPwa(){const install=$('#adminInstallBtn');window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();adminDeferredInstall=e;if(install)install.hidden=false});window.addEventListener('appinstalled',()=>{adminDeferredInstall=null;if(install)install.hidden=true});if(install)install.onclick=async()=>{if(!adminDeferredInstall)return;adminDeferredInstall.prompt();await adminDeferredInstall.userChoice.catch(()=>{});adminDeferredInstall=null;install.hidden=true};if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('/admin/admin-sw.js',{scope:'/admin/',updateViaCache:'none'}).then(r=>r.update()).catch(()=>{}),{once:true})}
async function renderAdminOverview(){const box=$('#adminOverview');if(!box)return;box.innerHTML=`<div class="admin-overview-loading"><i class="bi bi-arrow-repeat"></i> A carregar indicadores...</div>`;try{const s=await api('/api/admin/analytics/summary');const cards=[['Profissionais pendentes',s.pendingProfiles||0,'bi-person-check','moderacao'],['Serviços em análise',s.pendingServices||0,'bi-briefcase','moderacao'],['Projetos em análise',s.pendingProjects||0,'bi-images','moderacao'],['Denúncias abertas',s.openReports||0,'bi-shield-exclamation','denuncias'],['Visualizações · 30 dias',s.views30||0,'bi-eye','desempenho'],['Contactos · 30 dias',s.contacts30||0,'bi-chat-dots','desempenho']];box.innerHTML=`<div class="admin-command-center"><div class="command-copy"><span class="eyebrow">CENTRO DE CONTROLO</span><h3>O que precisa da sua atenção</h3><p>Indicadores operacionais da plataforma em tempo real.</p></div><div class="admin-kpi-grid">${cards.map(([label,value,icon,tab])=>`<button type="button" class="admin-kpi-card" data-overview-tab="${tab}"><span class="kpi-icon"><i class="bi ${icon}"></i></span><strong>${Number(value).toLocaleString('pt-PT')}</strong><small>${esc(label)}</small></button>`).join('')}</div>${Array.isArray(s.topCategories)&&s.topCategories.length?`<div class="admin-top-categories"><b>Categorias com mais procura</b><div>${s.topCategories.slice(0,5).map((c,i)=>`<span>${i+1}. ${esc(c.category||c.name||'Sem categoria')} <strong>${Number(c.count||c.total||0)}</strong></span>`).join('')}</div></div>`:''}</div>`;$$('[data-overview-tab]',box).forEach(b=>b.onclick=()=>setAdminTab(b.dataset.overviewTab))}catch(e){box.innerHTML=`<div class="admin-overview-loading error"><i class="bi bi-exclamation-triangle"></i> Indicadores indisponíveis: ${esc(e.message)}</div>`}}
async function init(){try{const s=await api('/api/admin/session');if(!s.authenticated)return location.replace('/admin/');data=await api('/api/site');applyAdminBrand();setupAdminShell();renderAll()}catch(e){console.error(e);const main=$('.admin-main')||document.querySelector('main');if(main)main.innerHTML=`<section class="panel"><h2>Não foi possível carregar o painel</h2><p>${esc(e.message||'Erro inesperado ao carregar os dados.')}</p><button type="button" id="retryAdminLoad">Tentar novamente</button></section>`;const retry=$('#retryAdminLoad');if(retry)retry.onclick=()=>location.reload()}}
$('#logout').onclick=async()=>{await api('/api/admin/logout',{method:'POST'}).catch(()=>{});location.replace('/admin/')};function renderAll(){applyAdminBrand();renderAdminOverview();renderSettings();renderServices();renderPortfolio();renderTeam();renderPartners();renderLinks();renderSocials();renderModeration();renderAnalytics();renderReports();renderRatings();renderAudit();renderCommunication();renderSecurity()}
async function refreshSiteData(){data=await api('/api/site');applyAdminBrand();return data}
async function confirmRemove(label='este item'){return uiConfirm(`Remover ${label}? Esta ação não pode ser desfeita.`,{title:'Confirmar remoção',confirmText:'Remover',danger:true})}
function renderSettings(){
  const s=data.settings||{},headerLight=s.headerLogoLight||s.headerLogo||s.logo||'',headerDark=s.headerLogoDark||s.headerLogo||s.logo||'',heroLogo=s.heroLogo||s.logo||'';
  $('#settingsAdmin').innerHTML=`<form class="panel form-grid" id="settingsForm">
    <label>Nome do site<input name="siteName" value="${esc(s.siteName||'Yuran Multicerviços')}"></label><label>Slogan<input name="tagline" value="${esc(s.tagline||'')}"></label>
    <label class="span-2">Título SEO / redes sociais<input name="seoTitle" value="${esc(s.seoTitle||'Yuran Multicerviços | Profissionais e serviços')}"></label><label class="span-2">Descrição SEO<textarea name="seoDescription" rows="2">${esc(s.seoDescription||'Encontre profissionais, serviços e trabalhos numa plataforma moderada e profissional.')}</textarea></label>
    <label class="span-2">Título principal<input name="heroTitle" value="${esc(s.heroTitle||'')}"></label><label class="span-2">Texto principal<textarea name="heroText" rows="3">${esc(s.heroText||'')}</textarea></label>
    <label>WhatsApp institucional<input name="whatsapp" value="${esc(s.whatsapp||'')}"></label><label>Telefone institucional<input name="phone" value="${esc(s.phone||'')}"></label><label>E-mail<input name="email" value="${esc(s.email||'')}"></label><label>Endereço / localização<input name="address" value="${esc(s.address||s.location||'')}"></label>
    <label>Cor principal do site<input name="primaryColor" type="color" value="${esc(s.primaryColor||'#151a16')}"></label><label>Cor do fundo principal<input name="heroColor" type="color" value="${esc(s.heroColor||'#00C9A7')}"></label><label>Cor hover do menu<input name="navHoverColor" type="color" value="${esc(s.navHoverColor||'#00C9A7')}"></label><label>Escurecimento do fundo (0 a 0.8)<input name="heroOverlay" type="number" min="0" max="0.8" step="0.05" value="${esc(s.heroOverlay??'0.24')}"></label>
    <label class="span-2">Sobre nós<textarea rows="7" name="about">${esc(s.about||'')}</textarea></label>
    <div class="span-2 admin-subpanel"><div class="admin-section-head"><div><h3>Vídeo de apresentação</h3><p class="help">Use um vídeo do YouTube. O vídeo só é carregado quando o visitante clicar em Play, evitando peso desnecessário na página inicial.</p></div></div>
      <label class="inline-check"><input type="checkbox" name="introVideoEnabled" ${s.introVideoEnabled?'checked':''}> Mostrar vídeo na página inicial</label>
      <label>Título<input name="introVideoTitle" value="${esc(s.introVideoTitle||'Conheça a Yuran Multicerviços')}"></label>
      <label>Link do YouTube<input name="introVideoUrl" value="${esc(s.introVideoUrl||'')}" placeholder="https://www.youtube.com/watch?v=..."></label>
      <label class="span-2">Apresentação<textarea name="introVideoText" rows="3">${esc(s.introVideoText||'')}</textarea></label>
    </div>
    <button class="span-2">Guardar informações e cores</button></form>
    <form class="panel visual-assets-grid asset-form" id="assetsForm">
      <div class="visual-asset-card"><b>Logo do menu — modo claro</b><small class="help">Versão preparada para a barra clara.</small>${headerLight?`<img class="asset-preview" src="${esc(headerLight)}">`:''}<input type="file" name="headerLogoLight" accept="image/jpeg,image/png,image/webp"></div>
      <div class="visual-asset-card"><b>Logo do menu — modo escuro</b><small class="help">Versão preparada para a barra escura.</small>${headerDark?`<img class="asset-preview dark-preview" src="${esc(headerDark)}">`:''}<input type="file" name="headerLogoDark" accept="image/jpeg,image/png,image/webp"></div>
      <div class="visual-asset-card"><b>Logotipo da área inicial</b><small class="help">Usado no destaque visual do início.</small>${heroLogo?`<img class="asset-preview" src="${esc(heroLogo)}">`:''}<input type="file" name="heroLogo" accept="image/jpeg,image/png,image/webp"></div>
      <div class="visual-asset-card"><b>Favicon</b><small class="help">Ícone exibido na aba do navegador.</small>${s.favicon?`<img class="favicon-preview" src="${esc(s.favicon)}">`:''}<input type="file" name="favicon" accept="image/jpeg,image/png,image/webp"></div>
      <div class="visual-asset-card visual-bg-card"><b>Imagem de fundo da área principal</b><small class="help">Se não houver imagem, será usada a cor configurada.</small>${s.heroBackgroundImage?`<img class="hero-bg-preview" src="${esc(s.heroBackgroundImage)}">`:''}<input type="file" name="heroBackground" accept="image/jpeg,image/png,image/webp">${s.heroBackgroundImage?'<label class="inline-check"><input type="checkbox" name="removeHeroBackground" value="1"> Remover imagem e usar apenas cor</label>':''}</div>
      <button class="visual-assets-submit">Guardar identidade visual e fundo</button></form>`;
  $('#settingsForm').onsubmit=async e=>{e.preventDefault();const btn=e.currentTarget.querySelector('button');await busyAction(btn,async()=>{try{const fd=new FormData(e.currentTarget),payload=Object.fromEntries(fd);payload.introVideoEnabled=fd.has('introVideoEnabled');data.settings=await api('/api/admin/settings',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});applyAdminBrand();await uiAlert('Informações guardadas.','Configurações atualizadas');renderSettings()}catch(err){await uiAlert(err.message,'Não foi possível guardar')}})};
  $('#assetsForm').onsubmit=async e=>{e.preventDefault();const btn=e.currentTarget.querySelector('button');await busyAction(btn,async()=>{try{data.settings=await api('/api/admin/settings/assets',{method:'POST',body:new FormData(e.currentTarget)});applyAdminBrand();renderSettings();await uiAlert('Logotipos e identidade visual atualizados.','Alterações guardadas')}catch(err){await uiAlert(err.message,'Não foi possível guardar')}})};
}
function renderServices(){
  const icons=['bi-lightning-charge','bi-palette','bi-megaphone','bi-flower1','bi-heart-pulse','bi-tools','bi-laptop','bi-buildings','bi-camera','bi-briefcase'];
  $('#servicesAdmin').innerHTML=`<form class="panel upload-form" id="serviceForm" enctype="multipart/form-data"><input name="title" placeholder="Nome do serviço" required><select name="iconClass">${icons.map(i=>`<option value="${i}">${i}</option>`).join('')}</select><label>Cor do serviço<input name="color" type="color" value="#00C9A7"></label><label>Ícone personalizado<input type="file" name="iconImage" accept="image/jpeg,image/png,image/webp"></label><label class="full">Banner da página do serviço<input type="file" name="banner" accept="image/jpeg,image/png,image/webp"></label><input class="full" name="description" placeholder="Descrição curta" required><textarea class="full" name="details" rows="6" placeholder="Descrição completa"></textarea><label class="full inline-check"><input type="checkbox" name="featured"> Mostrar este serviço na página inicial</label><button class="full">Adicionar serviço</button></form><div class="admin-grid">${data.services.map(s=>`<article class="admin-card" data-service-id="${esc(s.id)}"><div class="service-admin-head" style="--service-color:${esc(s.color||'#00C9A7')}"><span class="service-admin-icon">${serviceIcon(s)}</span><h3>${esc(s.title)}</h3></div>${s.featured!==false?'<span class="admin-featured"><i class="bi bi-star-fill"></i> Página inicial</span>':''}${s.banner?`<img src="${esc(s.banner)}" alt="">`:''}<p>${esc(s.description||'')}</p><details><summary>Editar serviço</summary><form class="stack edit-service-form" data-id="${esc(s.id)}"><input name="title" value="${esc(s.title)}" required><input name="iconClass" value="${esc(s.iconClass||'bi-briefcase')}" placeholder="Bootstrap icon"><label>Cor<input name="color" type="color" value="${esc(s.color||'#00C9A7')}"></label><textarea name="description" rows="3">${esc(s.description||'')}</textarea><textarea name="details" rows="6">${esc(s.details||s.description||'')}</textarea><label>Novo ícone<input type="file" name="iconImage" accept="image/jpeg,image/png,image/webp"></label><label>Novo banner<input type="file" name="banner" accept="image/jpeg,image/png,image/webp"></label><label class="inline-check"><input type="checkbox" name="featured" ${s.featured!==false?'checked':''}> Mostrar na página inicial</label><button>Guardar alterações</button></form></details><div class="actions"><a class="admin-link" target="_blank" href="/servico/${encodeURIComponent(s.id)}">Ver página ↗</a><button class="danger js-remove-service" type="button">Remover</button></div></article>`).join('')}</div>`;
  $('#serviceForm').onsubmit=async e=>{e.preventDefault();const btn=e.currentTarget.querySelector('button');await busyAction(btn,async()=>{try{await api('/api/admin/services',{method:'POST',body:new FormData(e.currentTarget)});await refreshSiteData();renderServices();renderPortfolio();e.currentTarget.reset()}catch(err){await uiAlert(err.message,'Erro ao adicionar serviço')}})};
  $$('.edit-service-form',$('#servicesAdmin')).forEach(f=>f.onsubmit=async e=>{e.preventDefault();const btn=f.querySelector('button');await busyAction(btn,async()=>{try{await api(`/api/admin/services/${encodeURIComponent(f.dataset.id)}`,{method:'PUT',body:new FormData(f)});await refreshSiteData();renderServices();renderPortfolio();await uiAlert('Serviço atualizado.','Alterações guardadas')}catch(err){await uiAlert(err.message,'Erro ao editar serviço')}})});
  $$('.js-remove-service',$('#servicesAdmin')).forEach(btn=>btn.onclick=async()=>{const card=btn.closest('[data-service-id]'),id=card.dataset.serviceId,name=card.querySelector('h3')?.textContent||'este serviço';if(!await confirmRemove(`o serviço “${name}”`))return;await busyAction(btn,async()=>{try{await api(`/api/admin/services/${encodeURIComponent(id)}`,{method:'DELETE'});await refreshSiteData();renderServices();renderPortfolio()}catch(err){await uiAlert(err.message,'Erro ao remover serviço')}})});
}
function renderPortfolio(){
  const options=data.services.map(s=>`<option value="${esc(s.title)}">${esc(s.title)}</option>`).join('');
  $('#portfolioAdmin').innerHTML=`<form class="panel upload-form" id="portfolioForm" enctype="multipart/form-data"><input name="title" placeholder="Título do projeto" required><select name="service" required><option value="">Serviço</option>${options}</select><label class="full">Imagens do projeto<input type="file" name="images" accept="image/jpeg,image/png,image/webp" multiple required></label><textarea class="full" name="description" rows="6" placeholder="Descrição completa"></textarea><label class="full inline-check"><input type="checkbox" name="featured"> Mostrar como trabalho em destaque na página inicial</label><button class="full">Publicar trabalho</button></form><div class="admin-grid">${data.portfolio.map(p=>{const imgs=p.images?.length?p.images:(p.image?[p.image]:[]);return`<article class="admin-card" data-portfolio-id="${esc(p.id)}">${imgs[0]?`<img src="${esc(imgs[0])}">`:''}<small>${esc(p.service||'')}</small><h3>${esc(p.title)}</h3>${p.featured?'<span class="admin-featured"><i class="bi bi-star-fill"></i> Em destaque</span>':''}<p>${esc(p.description||'')}</p><div class="mini">${imgs.length} imagem(ns)</div><details><summary>Editar projeto</summary><form class="stack edit-portfolio-form" data-id="${esc(p.id)}"><input name="title" value="${esc(p.title||'')}" required><select name="service"><option value="">Serviço</option>${data.services.map(s=>`<option value="${esc(s.title)}" ${s.title===p.service?'selected':''}>${esc(s.title)}</option>`).join('')}</select><textarea name="description" rows="5">${esc(p.description||'')}</textarea><label>Adicionar imagens<input type="file" name="images" accept="image/jpeg,image/png,image/webp" multiple></label><label class="inline-check"><input type="checkbox" name="replaceImages" value="1"> Substituir galeria atual pelas novas imagens</label><label class="inline-check"><input type="checkbox" name="featured" ${p.featured?'checked':''}> Trabalho em destaque</label><button>Guardar alterações</button></form></details><div class="actions"><button class="secondary js-toggle-portfolio" type="button" data-value="${!p.featured}">${p.featured?'Remover destaque':'Destacar'}</button><button class="danger js-remove-portfolio" type="button">Remover</button></div></article>`}).join('')}</div>`;
  $('#portfolioForm').onsubmit=async e=>{e.preventDefault();const btn=e.currentTarget.querySelector('button');await busyAction(btn,async()=>{try{await api('/api/admin/portfolio',{method:'POST',body:new FormData(e.currentTarget)});await refreshSiteData();renderPortfolio();e.currentTarget.reset()}catch(err){await uiAlert(err.message,'Erro ao publicar projeto')}})};
  $$('.edit-portfolio-form',$('#portfolioAdmin')).forEach(f=>f.onsubmit=async e=>{e.preventDefault();const btn=f.querySelector('button');await busyAction(btn,async()=>{try{await api(`/api/admin/portfolio/${encodeURIComponent(f.dataset.id)}`,{method:'PUT',body:new FormData(f)});await refreshSiteData();renderPortfolio();await uiAlert('Projeto atualizado.','Alterações guardadas')}catch(err){await uiAlert(err.message,'Erro ao editar projeto')}})});
  $$('.js-toggle-portfolio',$('#portfolioAdmin')).forEach(btn=>btn.onclick=async()=>{const id=btn.closest('[data-portfolio-id]').dataset.portfolioId;await busyAction(btn,async()=>{try{await api(`/api/admin/portfolio/${encodeURIComponent(id)}/featured`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({featured:btn.dataset.value==='true'})});await refreshSiteData();renderPortfolio()}catch(err){await uiAlert(err.message,'Erro ao alterar destaque')}})});
  $$('.js-remove-portfolio',$('#portfolioAdmin')).forEach(btn=>btn.onclick=async()=>{const card=btn.closest('[data-portfolio-id]'),id=card.dataset.portfolioId,name=card.querySelector('h3')?.textContent||'este projeto';if(!await confirmRemove(`o projeto “${name}” e as respetivas imagens`))return;await busyAction(btn,async()=>{try{await api(`/api/admin/portfolio/${encodeURIComponent(id)}`,{method:'DELETE'});await refreshSiteData();renderPortfolio()}catch(err){await uiAlert(err.message,'Erro ao remover projeto')}})});
}
function renderTeam(){
  $('#teamAdmin').innerHTML=`<form class="panel upload-form" id="teamForm"><input name="name" placeholder="Nome" required><input name="role" placeholder="Função / especialidade" required><label class="full">Foto<input type="file" name="photo" accept="image/jpeg,image/png,image/webp"></label><textarea class="full" name="bio" placeholder="Breve biografia"></textarea><button class="full">Adicionar membro da equipa</button></form><div class="admin-grid">${data.team.map(m=>`<article class="admin-card" data-team-id="${esc(m.id)}">${m.photo?`<img src="${esc(m.photo)}">`:''}<h3>${esc(m.name)}</h3><small>${esc(m.role)}</small><p>${esc(m.bio||'')}</p><details><summary>Editar membro</summary><form class="stack edit-team-form" data-id="${esc(m.id)}"><input name="name" value="${esc(m.name||'')}" required><input name="role" value="${esc(m.role||'')}" required><textarea name="bio" rows="4">${esc(m.bio||'')}</textarea><label>Nova fotografia<input type="file" name="photo" accept="image/jpeg,image/png,image/webp"></label><button>Guardar alterações</button></form></details><div class="actions"><button class="danger js-remove-team" type="button">Remover</button></div></article>`).join('')}</div>`;
  $('#teamForm').onsubmit=async e=>{e.preventDefault();const btn=e.currentTarget.querySelector('button');await busyAction(btn,async()=>{try{await api('/api/admin/team',{method:'POST',body:new FormData(e.currentTarget)});await refreshSiteData();renderTeam();e.currentTarget.reset()}catch(err){await uiAlert(err.message,'Erro ao adicionar membro')}})};
  $$('.edit-team-form',$('#teamAdmin')).forEach(f=>f.onsubmit=async e=>{e.preventDefault();const btn=f.querySelector('button');await busyAction(btn,async()=>{try{await api(`/api/admin/team/${encodeURIComponent(f.dataset.id)}`,{method:'PUT',body:new FormData(f)});await refreshSiteData();renderTeam();await uiAlert('Membro atualizado.','Alterações guardadas')}catch(err){await uiAlert(err.message,'Erro ao editar membro')}})});
  $$('.js-remove-team',$('#teamAdmin')).forEach(btn=>btn.onclick=async()=>{const card=btn.closest('[data-team-id]'),id=card.dataset.teamId,name=card.querySelector('h3')?.textContent||'este membro';if(!await confirmRemove(`“${name}” da equipa`))return;await busyAction(btn,async()=>{try{await api(`/api/admin/team/${encodeURIComponent(id)}`,{method:'DELETE'});await refreshSiteData();renderTeam()}catch(err){await uiAlert(err.message,'Erro ao remover membro')}})});
}
function renderPartners(){
  $('#partnersAdmin').innerHTML=`<form class="panel partner-upload-form" id="partnerForm"><input name="name" placeholder="Nome do parceiro" required><input name="url" placeholder="www.exemplo.com"><div class="partner-theme-upload"><b>Logotipo para modo claro</b><small class="help">Use a versão da marca com boa leitura sobre fundo claro.</small><input type="file" name="logoLight" accept="image/jpeg,image/png,image/webp"></div><div class="partner-theme-upload"><b>Logotipo para modo escuro</b><small class="help">Use a versão preparada para fundo escuro.</small><input type="file" name="logoDark" accept="image/jpeg,image/png,image/webp"></div><button class="full">Adicionar parceiro</button></form><div class="admin-grid">${data.partners.map(p=>{const light=p.logoLight||p.logo||'',dark=p.logoDark||p.logo||'';return`<article class="admin-card partner-admin-card" data-partner-id="${esc(p.id)}"><div class="partner-admin-previews"><div><small>Modo claro</small>${light?`<div class="partner-preview light"><img class="partner-admin-logo" src="${esc(light)}"></div>`:'<div class="partner-preview light empty">Sem logotipo</div>'}</div><div><small>Modo escuro</small>${dark?`<div class="partner-preview dark"><img class="partner-admin-logo" src="${esc(dark)}"></div>`:'<div class="partner-preview dark empty">Sem logotipo</div>'}</div></div><h3>${esc(p.name)}</h3><p>${esc(p.url||'')}</p><details><summary>Editar parceiro</summary><form class="stack edit-partner-form" data-id="${esc(p.id)}"><input name="name" value="${esc(p.name||'')}" required><input name="url" value="${esc(p.url||'')}"><label>Novo logo claro<input type="file" name="logoLight" accept="image/jpeg,image/png,image/webp"></label><label>Novo logo escuro<input type="file" name="logoDark" accept="image/jpeg,image/png,image/webp"></label><button>Guardar alterações</button></form></details><button class="danger js-remove-partner" type="button">Remover</button></article>`}).join('')}</div>`;
  $('#partnerForm').onsubmit=async e=>{e.preventDefault();const btn=e.currentTarget.querySelector('button');await busyAction(btn,async()=>{try{await api('/api/admin/partners',{method:'POST',body:new FormData(e.currentTarget)});await refreshSiteData();renderPartners();e.currentTarget.reset()}catch(err){await uiAlert(err.message,'Erro ao adicionar parceiro')}})};
  $$('.edit-partner-form',$('#partnersAdmin')).forEach(f=>f.onsubmit=async e=>{e.preventDefault();const btn=f.querySelector('button');await busyAction(btn,async()=>{try{await api(`/api/admin/partners/${encodeURIComponent(f.dataset.id)}`,{method:'PUT',body:new FormData(f)});await refreshSiteData();renderPartners();await uiAlert('Parceiro atualizado.','Alterações guardadas')}catch(err){await uiAlert(err.message,'Erro ao editar parceiro')}})});
  $$('.js-remove-partner',$('#partnersAdmin')).forEach(btn=>btn.onclick=async()=>{const card=btn.closest('[data-partner-id]'),id=card.dataset.partnerId,name=card.querySelector('h3')?.textContent||'este parceiro';if(!await confirmRemove(`o parceiro “${name}”`))return;await busyAction(btn,async()=>{try{await api(`/api/admin/partners/${encodeURIComponent(id)}`,{method:'DELETE'});await refreshSiteData();renderPartners()}catch(err){await uiAlert(err.message,'Erro ao remover parceiro')}})});
}
function renderLinks(){
  $('#linksAdmin').innerHTML=`<form class="panel upload-form" id="linkForm"><input name="title" placeholder="Título" required><input name="url" placeholder="https://..." required><label class="full">Ícone<select name="iconClass">${iconOptions.map(i=>`<option value="${i}">${i}</option>`).join('')}</select></label><button class="full">Adicionar ligação</button></form><div class="admin-grid">${data.links.map(l=>`<article class="admin-card" data-link-id="${esc(l.id)}"><h3><i class="bi ${esc(l.iconClass||'bi-link-45deg')}"></i> ${esc(l.title)}</h3><p>${esc(l.url)}</p><details><summary>Editar ligação</summary><form class="stack edit-link-form" data-id="${esc(l.id)}"><input name="title" value="${esc(l.title||'')}" required><input name="url" value="${esc(l.url||'')}" required><select name="iconClass">${iconOptions.map(i=>`<option value="${i}" ${i===(l.iconClass||'bi-link-45deg')?'selected':''}>${i}</option>`).join('')}</select><button>Guardar alterações</button></form></details><button class="danger js-remove-link" type="button">Remover</button></article>`).join('')}</div>`;
  $('#linkForm').onsubmit=async e=>{e.preventDefault();const btn=e.currentTarget.querySelector('button');await busyAction(btn,async()=>{try{await api('/api/admin/links',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))});await refreshSiteData();renderLinks();e.currentTarget.reset()}catch(err){await uiAlert(err.message,'Erro ao adicionar ligação')}})};
  $$('.edit-link-form',$('#linksAdmin')).forEach(f=>f.onsubmit=async e=>{e.preventDefault();const btn=f.querySelector('button');await busyAction(btn,async()=>{try{await api(`/api/admin/links/${encodeURIComponent(f.dataset.id)}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(f)))});await refreshSiteData();renderLinks();await uiAlert('Ligação atualizada.','Alterações guardadas')}catch(err){await uiAlert(err.message,'Erro ao editar ligação')}})});
  $$('.js-remove-link',$('#linksAdmin')).forEach(btn=>btn.onclick=async()=>{const card=btn.closest('[data-link-id]'),id=card.dataset.linkId,name=card.querySelector('h3')?.textContent?.trim()||'esta ligação';if(!await confirmRemove(`a ligação “${name}”`))return;await busyAction(btn,async()=>{try{await api(`/api/admin/links/${encodeURIComponent(id)}`,{method:'DELETE'});await refreshSiteData();renderLinks()}catch(err){await uiAlert(err.message,'Erro ao remover ligação')}})});
}
function renderSocials(){
  data.socials||=[];
  $('#socialsAdmin').innerHTML=`<form class="panel upload-form" id="socialForm"><label>Plataforma<select name="platform" id="socialPlatform">${Object.keys(socialPlatforms).map(n=>`<option value="${n}">${n}</option>`).join('')}</select></label><input name="url" placeholder="https://..." required><input type="hidden" name="iconClass" id="socialIconClass" value="bi-instagram"><button class="full">Adicionar rede social</button></form><div class="admin-grid">${data.socials.map(x=>`<article class="admin-card social-admin-card" data-social-id="${esc(x.id)}"><div class="social-preview"><i class="bi ${esc(x.iconClass||socialPlatforms[x.platform]||'bi-link-45deg')}"></i></div><h3>${esc(x.platform||'Rede social')}</h3><p>${esc(x.url||'')}</p><details><summary>Editar rede social</summary><form class="stack edit-social-form" data-id="${esc(x.id)}"><select name="platform">${Object.keys(socialPlatforms).map(n=>`<option value="${n}" ${n===x.platform?'selected':''}>${n}</option>`).join('')}</select><input name="url" value="${esc(x.url||'')}" required><button>Guardar alterações</button></form></details><button class="danger js-remove-social" type="button">Remover</button></article>`).join('')}</div>`;
  const sel=$('#socialPlatform'),hidden=$('#socialIconClass');sel.onchange=()=>hidden.value=socialPlatforms[sel.value]||'bi-link-45deg';
  $('#socialForm').onsubmit=async e=>{e.preventDefault();const btn=e.currentTarget.querySelector('button');await busyAction(btn,async()=>{try{await api('/api/admin/socials',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))});await refreshSiteData();renderSocials();e.currentTarget.reset();sel.dispatchEvent(new Event('change'))}catch(err){await uiAlert(err.message,'Erro ao adicionar rede social')}})};
  $$('.edit-social-form',$('#socialsAdmin')).forEach(f=>f.onsubmit=async e=>{e.preventDefault();const btn=f.querySelector('button'),v=Object.fromEntries(new FormData(f));v.iconClass=socialPlatforms[v.platform]||'bi-link-45deg';await busyAction(btn,async()=>{try{await api(`/api/admin/socials/${encodeURIComponent(f.dataset.id)}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(v)});await refreshSiteData();renderSocials();await uiAlert('Rede social atualizada.','Alterações guardadas')}catch(err){await uiAlert(err.message,'Erro ao editar rede social')}})});
  $$('.js-remove-social',$('#socialsAdmin')).forEach(btn=>btn.onclick=async()=>{const card=btn.closest('[data-social-id]'),id=card.dataset.socialId,name=card.querySelector('h3')?.textContent||'esta rede social';if(!await confirmRemove(`“${name}”`))return;await busyAction(btn,async()=>{try{await api(`/api/admin/socials/${encodeURIComponent(id)}`,{method:'DELETE'});await refreshSiteData();renderSocials()}catch(err){await uiAlert(err.message,'Erro ao remover rede social')}})});
}
async function renderModeration(){
  const box=$('#moderationAdmin');if(!box)return;
  box.innerHTML='<div class="panel">A carregar moderação...</div>';
  try{
    const m=await api('/api/admin/moderation');
    const pending=m.professionals.filter(x=>x.status==='pending').length;
    const professionals=`<div class="panel"><div class="admin-section-head"><div><h3>Profissionais <span class="mini">(${m.professionals.length})</span></h3><p class="help">${pending} perfil(is) aguardando decisão. Valide primeiro a identidade e depois aprove o perfil quando os dados estiverem adequados.</p></div></div><div class="moderation-list">${m.professionals.map(x=>{
      const completion=Number(x.profile_completeness||0),docsDeleted=!!x.identity_documents_deleted_at;
      return `<article class="moderation-item identity-review" data-professional-id="${esc(x.id)}"><div class="moderation-main"><div class="moderation-name-row"><b>${esc(x.name)}</b>${x.profile_type==='founder'?'<span class="admin-founder"><i class="bi bi-gem"></i> Fundador</span>':''}${x.official_profile?'<span class="admin-official"><i class="bi bi-building-check"></i> Perfil oficial</span>':''}${x.featured?'<span class="admin-featured"><i class="bi bi-star-fill"></i> Destaque</span>':''}</div><p>${esc(x.specialty||x.email||'')}</p><div class="completion-admin"><span><i style="width:${completion}%"></i></span><b>${completion}% completo</b></div><div class="identity-state"><span class="mod-status ${esc(x.verification_status||'pending')}">Identidade: ${verificationLabel[x.verification_status]||'Em análise'}</span>${x.verification_reason?`<p class="mod-reason">${esc(x.verification_reason)}</p>`:''}<div class="identity-private-facts">${x.birth_date?`<span><i class="bi bi-calendar3"></i> Nascimento: ${new Date(x.birth_date+'T00:00:00').toLocaleDateString('pt-PT')}</span>`:''}${x.id_number?`<span><i class="bi bi-person-vcard"></i> Documento: ${esc(x.id_number)}</span>`:''}</div></div>${docsDeleted?'<p class="help"><i class="bi bi-shield-check"></i> Documentos eliminados após o período de retenção.</p>':`<div class="doc-actions"><button type="button" class="secondary" data-action="open-doc" data-side="front">Ver frente</button><button type="button" class="secondary" data-action="open-doc" data-side="back">Ver verso</button><button type="button" data-action="verify-identity" data-status="approved">Validar identidade</button><button type="button" class="danger" data-action="verify-identity" data-status="rejected">Rejeitar documento</button></div>`}${x.identity_retention_until&&!docsDeleted?`<small>Retenção prevista até ${new Date(x.identity_retention_until).toLocaleDateString('pt-PT')}</small>`:''}${x.rejection_reason?`<p class="mod-reason">Perfil: ${esc(x.rejection_reason)}</p>`:''}
      <details class="admin-prof-edit"><summary>Editar dados do profissional</summary><form class="admin-prof-form stack" data-id="${esc(x.id)}"><div class="form-grid"><label>Nome<input name="name" value="${esc(x.name||'')}" required></label><label>Especialidade<input name="specialty" value="${esc(x.specialty||'')}"></label><label>Endereço privado<input name="address" value="${esc(x.address||'')}"></label><label>Localização pública<input name="location" value="${esc(x.location||'')}"></label><label>Celular<input name="phone" value="${esc(x.phone||'')}"></label><label>WhatsApp<input name="whatsapp" value="${esc(x.whatsapp||'')}"></label><label>Data de nascimento<input name="birth_date" type="date" value="${esc(x.birth_date||'')}"></label><label>Número de identificação<input name="id_number" value="${esc(x.id_number||'')}"></label><label class="span-2">Área de atendimento<input name="service_area" value="${esc(x.service_area||'')}"></label><label>Anos de experiência<input name="years_experience" type="number" min="0" max="80" value="${Number(x.years_experience||0)}"></label><label>Disponibilidade<select name="availability"><option value="available" ${x.availability==='available'?'selected':''}>Disponível</option><option value="limited" ${x.availability==='limited'?'selected':''}>Limitada</option><option value="unavailable" ${x.availability==='unavailable'?'selected':''}>Indisponível</option></select></label><label>Tipo de perfil<select name="profile_type"><option value="professional" ${(!x.profile_type||x.profile_type==='professional')?'selected':''}>Profissional</option><option value="team" ${x.profile_type==='team'?'selected':''}>Membro da equipa</option><option value="founder" ${x.profile_type==='founder'?'selected':''}>Fundador</option><option value="institutional" ${x.profile_type==='institutional'?'selected':''}>Conta institucional</option></select></label><label>Cargo institucional<input name="institutional_role" value="${esc(x.institutional_role||'')}" placeholder="Ex.: Fundador da Yuran Multicerviços"></label><label class="span-2 inline-check"><input type="checkbox" name="official_profile" ${x.official_profile?'checked':''}> Marcar como perfil oficial da plataforma</label><label class="span-2">Mensagem institucional / Sobre o fundador<textarea name="founder_message" rows="3">${esc(x.founder_message||'')}</textarea></label><label class="span-2">Título/Frase profissional<input name="headline" value="${esc(x.headline||'')}"></label><label class="span-2">Competências<input name="skills" value="${esc(x.skills||'')}"></label><label class="span-2">Idiomas<input name="languages" value="${esc(x.languages||'')}"></label><label class="span-2">Formação/certificações<textarea name="certifications" rows="2">${esc(x.certifications||'')}</textarea></label><label class="span-2">Apresentação profissional<textarea name="bio" rows="5">${esc(x.bio||'')}</textarea></label></div><button>Guardar alterações</button></form></details></div>
      <div class="moderation-actions"><span class="mod-status ${esc(x.status)}">${statusLabel[x.status]||esc(x.status)}</span>${x.status==='approved'?`<a class="admin-link" target="_blank" href="/profissional/${encodeURIComponent(x.slug)}">Ver perfil ↗</a>`:''}<button type="button" data-action="moderate" data-status="approved">Aprovar perfil</button><button type="button" class="secondary" data-action="toggle-verified" data-value="${!x.verified}">${x.verified?'Remover selo':'Atribuir selo verificado'}</button>${x.status==='approved'?`<button type="button" class="secondary" data-action="feature" data-type="professionals" data-value="${!x.featured}">${x.featured?'Remover destaque':'Destacar profissional'}</button>`:''}<button type="button" data-action="moderate" data-status="rejected">Rejeitar</button><button type="button" class="danger" data-action="moderate" data-status="suspended">Suspender</button><button type="button" class="danger outline-danger" data-action="delete-professional"><i class="bi bi-trash3"></i> Excluir conta</button></div></article>`}).join('')||'<p>Nenhum profissional.</p>'}</div></div>`;
    const section=(title,type,items)=>`<div class="panel"><h3>${title} <span class="mini">(${items.length})</span></h3><div class="moderation-list">${items.map(x=>`<article class="moderation-item" data-item-id="${esc(x.id)}" data-item-type="${type}"><div><b>${esc(x.title||'Item')}</b>${x.professional_profiles?.name?`<small> por ${esc(x.professional_profiles.name)}</small>`:''}<p>${esc(x.category||x.description||'')}</p>${x.rejection_reason?`<p class="mod-reason">Motivo: ${esc(x.rejection_reason)}</p>`:''}${x.featured?'<span class="admin-featured"><i class="bi bi-star-fill"></i> Destaque</span>':''}</div><div class="moderation-actions"><span class="mod-status ${esc(x.status)}">${statusLabel[x.status]||esc(x.status)}</span><button type="button" data-action="moderate-item" data-status="approved">Aprovar</button><button type="button" data-action="moderate-item" data-status="rejected">Rejeitar</button><button type="button" class="danger" data-action="moderate-item" data-status="suspended">Suspender</button>${type==='projects'&&x.status==='approved'?`<button type="button" class="secondary" data-action="feature-item" data-value="${!x.featured}">${x.featured?'Remover destaque':'Destacar na página inicial'}</button>`:''}</div></article>`).join('')||'<p>Nenhum item.</p>'}</div></div>`;
    box.innerHTML=professionals+section('Serviços enviados','services',m.services)+section('Projetos enviados','projects',m.projects);

    box.onclick=async ev=>{
      const btn=ev.target.closest('button[data-action]');if(!btn)return;
      const prof=btn.closest('[data-professional-id]'),item=btn.closest('[data-item-id]');
      const action=btn.dataset.action;
      await busyAction(btn,async()=>{
        try{
          if(action==='open-doc'){
            const x=await api(`/api/admin/professionals/${prof.dataset.professionalId}/identity/${btn.dataset.side}`);window.open(x.url,'_blank','noopener');return;
          }
          if(action==='verify-identity'){
            let reason='';if(btn.dataset.status==='rejected'){reason=await uiPrompt('Explique ao profissional por que o documento foi rejeitado.',{title:'Rejeitar documento',placeholder:'Ex.: imagem ilegível, documento incompleto...',required:true,confirmText:'Rejeitar',danger:true});if(reason===null||!reason.trim())return}
            await api(`/api/admin/professionals/${prof.dataset.professionalId}/verification`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:btn.dataset.status,reason})});
          }else if(action==='moderate'){
            let reason='';const status=btn.dataset.status;if(status==='rejected'){reason=await uiPrompt('Informe o motivo da rejeição para que o profissional possa corrigir o conteúdo.',{title:'Rejeitar conteúdo',required:true,confirmText:'Continuar',danger:true});if(reason===null||!reason.trim())return}if(!await uiConfirm(`Confirmar alteração para “${statusLabel[status]||status}”?`,{title:'Confirmar moderação',danger:status==='rejected'}))return;
            await api(`/api/admin/moderation/professionals/${prof.dataset.professionalId}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status,rejection_reason:reason})});
          }else if(action==='toggle-verified'){
            const value=btn.dataset.value==='true';if(!await uiConfirm(value?'Atribuir o selo público de verificado a este profissional?':'Remover o selo público de verificado deste profissional?',{title:value?'Atribuir selo verificado':'Remover selo verificado',danger:!value}))return;
            await api(`/api/admin/professionals/${prof.dataset.professionalId}/verified`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({verified:value})});
          }else if(action==='feature'){
            const value=btn.dataset.value==='true';await api(`/api/admin/featured/professionals/${prof.dataset.professionalId}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({featured:value})});
          }else if(action==='delete-professional'){
            const name=prof.querySelector('.moderation-name-row b')?.textContent||'este profissional';if(!await uiConfirm(`Excluir definitivamente ${name}, os seus serviços, projetos, CV e documentos? Esta ação não pode ser desfeita.`,{title:'Excluir conta profissional',confirmText:'Excluir definitivamente',danger:true}))return;
            const reason=(await uiPrompt('Registe um motivo interno para esta exclusão (opcional).',{title:'Motivo da exclusão',confirmText:'Continuar',danger:true}))||'';
            await api(`/api/admin/professionals/${prof.dataset.professionalId}`,{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({reason})});
          }else if(action==='moderate-item'){
            let reason='';const status=btn.dataset.status;if(status==='rejected'){reason=await uiPrompt('Informe o motivo da rejeição para que o profissional possa corrigir o conteúdo.',{title:'Rejeitar conteúdo',required:true,confirmText:'Continuar',danger:true});if(reason===null||!reason.trim())return}if(!await uiConfirm(`Confirmar alteração para “${statusLabel[status]||status}”?`,{title:'Confirmar moderação',danger:status==='rejected'}))return;
            await api(`/api/admin/moderation/${item.dataset.itemType}/${item.dataset.itemId}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status,rejection_reason:reason})});
          }else if(action==='feature-item'){
            const value=btn.dataset.value==='true';await api(`/api/admin/featured/${item.dataset.itemType}/${item.dataset.itemId}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({featured:value})});
          }
          await Promise.all([renderModeration(),renderAnalytics()]);
        }catch(e){alert(e.message)}
      });
    };
    $$('.admin-prof-form',box).forEach(f=>f.onsubmit=async ev=>{ev.preventDefault();const submit=f.querySelector('button');await busyAction(submit,async()=>{try{await api(`/api/admin/professionals/${f.dataset.id}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify((()=>{const fd=new FormData(f),v=Object.fromEntries(fd);v.official_profile=fd.has('official_profile');return v})())});alert('Dados do profissional atualizados.');await Promise.all([renderModeration(),renderAnalytics()])}catch(e){alert(e.message)}})});
  }catch(e){box.innerHTML=`<div class="panel"><b>Erro ao carregar moderação:</b> ${esc(e.message)}<p>Atualize a página. Se o erro continuar, confira os logs do Render.</p></div>`}
}

async function renderAnalytics(){
  const box=$('#analyticsAdmin');if(!box)return;box.innerHTML='<div class="panel">A carregar desempenho...</div>';
  try{
    const [rows,summary]=await Promise.all([api('/api/admin/analytics'),api('/api/admin/analytics/summary')]);
    const cards=`<div class="admin-summary-grid">
      <article><span>Perfis pendentes</span><b>${summary.pendingProfiles||0}</b></article>
      <article><span>Serviços pendentes</span><b>${summary.pendingServices||0}</b></article>
      <article><span>Projetos pendentes</span><b>${summary.pendingProjects||0}</b></article>
      <article><span>Denúncias abertas</span><b>${summary.openReports||0}</b></article>
      <article><span>Visualizações · 30 dias</span><b>${summary.views30||0}</b></article>
      <article><span>Contactos · 30 dias</span><b>${summary.contacts30||0}</b></article>
    </div>`;
    const cats=(summary.topCategories||[]).length?`<div class="panel"><h3>Categorias com mais oferta</h3><div class="category-bars">${summary.topCategories.map((c,i,a)=>{const max=Math.max(...a.map(x=>x.count),1);return `<div><span>${esc(c.name)}</span><i><b style="width:${Math.round(c.count/max*100)}%"></b></i><strong>${c.count}</strong></div>`}).join('')}</div></div>`:'';
    const professionals=`<div class="analytics-grid">${rows.map(x=>`<article class="analytics-card"><div class="analytics-head"><div><h3>${esc(x.name)}</h3><small>${esc(statusLabel[x.status]||x.status)} ${x.verified?'• selo verificado':''}</small></div><a class="admin-link" target="_blank" href="/profissional/${encodeURIComponent(x.slug)}">Perfil ↗</a></div><div class="metric-mini-grid"><div><b>${x.views}</b><span>Visualizações</span></div><div><b>${x.contacts}</b><span>Contactos</span></div><div><b>${Number(x.ratingAvg||0).toFixed(1)}</b><span>Avaliação (${x.ratingCount})</span></div><div><b>${x.openReports}</b><span>Denúncias abertas</span></div></div>${x.warning_count?`<p class="mod-reason">Advertências: ${x.warning_count}</p>`:''}</article>`).join('')||'<div class="panel">Ainda não há profissionais.</div>'}</div>`;
    box.innerHTML=cards+cats+professionals;
  }catch(e){box.innerHTML=`<div class="panel"><b>Erro:</b> ${esc(e.message)}</div>`}
}

async function renderReports(){
  const box=$('#reportsAdmin');if(!box)return;box.innerHTML='<div class="panel">A carregar denúncias...</div>';
  try{
    const rows=await api('/api/admin/reports');
    box.innerHTML=`<div class="panel"><div class="report-list">${rows.map(r=>`<article class="report-item ${esc(r.status)}"><div><div class="report-topline"><span class="mod-status ${r.status==='open'?'rejected':'approved'}">${r.status==='open'?'Em análise':esc(r.status)}</span>${r.protocol?`<code>${esc(r.protocol)}</code>`:''}</div><h3>${esc(r.professional_profiles?.name||'Profissional')}</h3><b>${esc(r.reason)}</b><p>${esc(r.details||'Sem detalhes.')}</p>${r.reporter_contact?`<small>Contacto do denunciante: ${esc(r.reporter_contact)}</small>`:''}<small>Recebida: ${new Date(r.created_at).toLocaleString('pt-PT')}</small></div><div class="report-actions">${r.status==='open'?`<button data-report-id="${esc(r.id)}" data-report-action="warn">Advertir</button><button class="secondary" data-report-id="${esc(r.id)}" data-report-action="suspend">Suspender temporariamente</button><button class="secondary" data-report-id="${esc(r.id)}" data-report-action="dismiss">Arquivar sem ação</button><button class="danger" data-report-id="${esc(r.id)}" data-report-action="delete">Excluir profissional</button>`:`<span class="mini">Ação: ${esc(r.admin_action||r.status)}</span>`}</div></article>`).join('')||'<p>Nenhuma denúncia recebida.</p>'}</div></div>`;
    $$('[data-report-action]',box).forEach(btn=>btn.onclick=()=>window.reportAction(btn.dataset.reportId,btn.dataset.reportAction));
  }catch(e){box.innerHTML=`<div class="panel"><b>Erro:</b> ${esc(e.message)}</div>`}
}
window.reportAction=async(id,action)=>{let reason='',suspensionDays=7;if(action==='warn'){reason=await uiPrompt('Escreva a advertência que será enviada ao profissional.',{title:'Advertir profissional',required:true,confirmText:'Enviar advertência'});if(reason===null)return}if(action==='suspend'){const days=await uiPrompt('Informe quantos dias a conta ficará suspensa.',{title:'Suspensão temporária',defaultValue:'7',inputType:'number',multiline:false,required:true,confirmText:'Continuar',danger:true});if(days===null)return;suspensionDays=Math.max(1,Number(days||7));reason=await uiPrompt('Informe o motivo da suspensão. Esta informação será comunicada ao profissional.',{title:'Motivo da suspensão',required:true,confirmText:'Suspender',danger:true});if(reason===null)return}if(action==='delete'&&!await uiConfirm('Excluir definitivamente este profissional e todos os seus conteúdos?',{title:'Excluir profissional',confirmText:'Excluir definitivamente',danger:true}))return;if(action==='dismiss'&&!await uiConfirm('Arquivar esta denúncia sem aplicar ação disciplinar?',{title:'Arquivar denúncia'}))return;try{await api(`/api/admin/reports/${id}/action`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,reason,suspensionDays})});renderReports();renderAnalytics();renderModeration()}catch(e){alert(e.message)}};

async function renderRatings(){
  const box=$('#ratingsAdmin');if(!box)return;box.innerHTML='<div class="panel">A carregar avaliações...</div>';
  try{
    const rows=await api('/api/admin/ratings');
    box.innerHTML=`<div class="panel"><div class="rating-admin-list">${rows.map(r=>`<article class="rating-admin-item"><div><div class="rating-admin-head"><span class="stars-admin">${'★'.repeat(Number(r.stars||0))}${'☆'.repeat(Math.max(0,5-Number(r.stars||0)))}</span><span class="mod-status ${r.status==='published'?'approved':'suspended'}">${r.status==='published'?'Publicada':'Oculta'}</span>${r.verified_interaction?'<span class="verified-interaction"><i class="bi bi-check-circle"></i> Interação registada</span>':''}</div><h3>${esc(r.professional_profiles?.name||'Profissional')}</h3>${r.professional_services?.title?`<small>Serviço: ${esc(r.professional_services.title)}</small>`:'<small>Avaliação geral</small>'}<p>${esc(r.comment||'Sem comentário.')}</p>${r.professional_reply?`<div class="reply-preview"><b>Resposta do profissional</b><p>${esc(r.professional_reply)}</p></div>`:''}<small>${new Date(r.created_at).toLocaleString('pt-PT')}</small></div><div class="moderation-actions">${r.status==='published'?`<button class="secondary" data-rating-id="${esc(r.id)}" data-rating-status="hidden">Ocultar</button>`:`<button data-rating-id="${esc(r.id)}" data-rating-status="published">Republicar</button>`}</div></article>`).join('')||'<p>Nenhuma avaliação recebida.</p>'}</div></div>`;
    $$('[data-rating-status]',box).forEach(btn=>btn.onclick=()=>window.setRatingStatus(btn.dataset.ratingId,btn.dataset.ratingStatus));
  }catch(e){box.innerHTML=`<div class="panel"><b>Erro:</b> ${esc(e.message)}</div>`}
}
window.setRatingStatus=async(id,status)=>{let reason='';if(status==='hidden'){const value=await uiPrompt('Registe o motivo interno para ocultar esta avaliação (opcional).',{title:'Ocultar avaliação',confirmText:'Ocultar',danger:true});if(value===null)return;reason=value}try{await api(`/api/admin/ratings/${id}/status`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status,reason})});renderRatings()}catch(e){alert(e.message)}};

async function renderAudit(){
  const box=$('#auditAdmin');if(!box)return;box.innerHTML='<div class="panel">A carregar histórico...</div>';
  try{
    const rows=await api('/api/admin/audit');
    box.innerHTML=`<div class="panel"><div class="audit-list">${rows.map(x=>`<article><div class="audit-icon"><i class="bi bi-shield-check"></i></div><div><b>${esc(x.action||'Ação administrativa')}</b><p>${esc(x.target_type||'item')} · ${esc(x.target_id||'')}</p>${x.reason?`<small>Motivo: ${esc(x.reason)}</small>`:''}<small>${new Date(x.created_at).toLocaleString('pt-PT')}</small></div></article>`).join('')||'<p>Ainda não existem registos de auditoria.</p>'}</div></div>`;
  }catch(e){box.innerHTML=`<div class="panel"><b>Erro:</b> ${esc(e.message)}</div>`}
}

async function renderCommunication(){
  const box=$('#communicationAdmin');if(!box)return;box.innerHTML='<div class="panel">A carregar centro de comunicação...</div>';
  try{
    const x=await api('/api/admin/email-center'),professionals=x.professionals||[],logs=x.logs||[];
    box.innerHTML=`<div class="communication-grid"><div class="panel"><div class="communication-status ${x.configured?'ready':'pending'}"><i class="bi ${x.configured?'bi-check-circle-fill':'bi-exclamation-triangle'}"></i><div><b>${x.configured?'Envio automático de e-mail ativo':'E-mail ainda não configurado'}</b><p>${x.configured?`Remetente configurado: ${esc(x.from||'')}${x.testMode?' · Modo de teste Resend':''}`:(esc(x.warning||'As notificações internas continuam funcionando. Configure RESEND_API_KEY e EMAIL_FROM no Render.'))}</p></div></div><form id="adminEmailForm" class="email-compose-form"><label>Destinatários<select name="audience" id="emailAudience"><option value="individual">Um profissional</option><option value="all">Todos os profissionais</option></select></label><label id="emailProfessionalWrap">Profissional<select name="professional_id" id="emailProfessional"><option value="">Selecionar profissional...</option>${professionals.map(p=>`<option value="${esc(p.id)}">${esc(p.name)} — ${esc(p.email||'sem e-mail')}</option>`).join('')}</select></label><label>Assunto<input name="subject" maxlength="160" placeholder="Ex.: Atualização importante da sua conta" required></label><label>Mensagem<textarea name="message" rows="8" maxlength="5000" placeholder="Escreva a mensagem que o profissional receberá por e-mail e no centro de notificações." required></textarea></label><div class="email-compose-note"><i class="bi bi-info-circle"></i><span>O envio administrativo cria também uma notificação dentro da Área Profissional. Para envio a todos, confirme cuidadosamente o conteúdo antes de continuar.</span></div><button ${x.configured?'':'disabled'}><i class="bi bi-send"></i> Enviar mensagem</button></form></div><div class="panel"><div class="admin-section-head"><div><h3>Envios recentes</h3><p class="help">Histórico das últimas comunicações administrativas.</p></div></div><div class="email-log-list">${logs.map(l=>`<article><div><b>${esc(l.subject)}</b><small>${l.audience==='all'?'Todos os profissionais':'Envio individual'} · ${new Date(l.created_at).toLocaleString('pt-PT')}</small></div><div class="email-log-counts"><span>${Number(l.sent_count||0)} enviados</span>${Number(l.failed_count||0)?`<span class="fail">${Number(l.failed_count)} falharam</span>`:''}</div></article>`).join('')||'<p class="help">Ainda não existem envios administrativos.</p>'}</div></div></div>`;
    const audience=$('#emailAudience'),wrap=$('#emailProfessionalWrap'),professional=$('#emailProfessional');const syncAudience=()=>{const all=audience.value==='all';wrap.hidden=all;professional.required=!all};audience.onchange=syncAudience;syncAudience();
    $('#adminEmailForm').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,values=Object.fromEntries(new FormData(form));if(values.audience==='individual'&&!values.professional_id)return uiAlert('Selecione um profissional.','Destinatário necessário');const target=values.audience==='all'?`todos os ${professionals.length} profissionais`:(professional.options[professional.selectedIndex]?.text||'profissional selecionado');if(!await uiConfirm(`Enviar “${values.subject}” para ${target}? A mensagem também aparecerá nas notificações internas.`,{title:'Confirmar envio',confirmText:'Enviar agora'}))return;const btn=form.querySelector('button[type="submit"],button:not([type])');await busyAction(btn,async()=>{try{const result=await api('/api/admin/emails/send',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(values)});await uiAlert(`Comunicação concluída. ${result.sent} e-mail(s) enviado(s) de ${result.recipients} destinatário(s).${result.failed?` ${result.failed} envio(s) falharam, mas a notificação interna foi registada.${result.errors?.length?` Motivo: ${result.errors.join(' | ')}`:''}`:''}`,'Mensagem enviada');renderCommunication()}catch(err){await uiAlert(err.message,'Não foi possível enviar')}})};
  }catch(e){box.innerHTML=`<div class="panel"><b>Erro:</b> ${esc(e.message)}</div>`}
}

async function renderSecurity(){
  const box=$('#securityAdmin');if(!box)return;
  let requests=[],twofa={enabled:false},health={security:{}};
  try{[requests,twofa,health]=await Promise.all([api('/api/admin/password-reset-requests'),api('/api/admin/2fa/status'),api('/health')])}catch{}
  box.innerHTML=`
  <div class="panel security-overview"><div class="admin-section-head"><div><h3>Estado de segurança</h3><p class="help">Verificações técnicas básicas do ambiente atual.</p></div></div><div class="security-check-grid"><span class="${health.security?.sessionSecretConfigured?'ok':'warn'}"><i class="bi ${health.security?.sessionSecretConfigured?'bi-check-circle-fill':'bi-exclamation-triangle-fill'}"></i> SESSION_SECRET ${health.security?.sessionSecretConfigured?'configurada':'temporária — configure no Render'}</span><span class="${health.security?.totpEncryptionKeyConfigured?'ok':'warn'}"><i class="bi ${health.security?.totpEncryptionKeyConfigured?'bi-check-circle-fill':'bi-exclamation-triangle-fill'}"></i> Chave exclusiva do 2FA ${health.security?.totpEncryptionKeyConfigured?'configurada':'não configurada'}</span><span class="ok"><i class="bi bi-check-circle-fill"></i> Cookies seguros em produção</span><span class="ok"><i class="bi bi-check-circle-fill"></i> Proteção de origem ativa</span><span class="ok"><i class="bi bi-check-circle-fill"></i> Validação de assinatura de uploads</span><span class="${twofa.enabled?'ok':'warn'}"><i class="bi ${twofa.enabled?'bi-check-circle-fill':'bi-exclamation-triangle-fill'}"></i> 2FA ${twofa.enabled?'ativada':'ainda não ativada'}</span></div></div>
  <div class="security-admin-grid">
    <form class="panel security-form" id="passwordForm"><span class="security-icon"><i class="bi bi-key"></i></span><h3>Senha do administrador</h3><p class="help">Use uma senha longa e exclusiva para este painel.</p><input type="password" name="currentPassword" placeholder="Senha atual" required><input type="password" name="newPassword" minlength="8" placeholder="Nova senha" required><input type="password" name="confirmPassword" minlength="8" placeholder="Confirmar nova senha" required><button>Alterar senha</button></form>
    <div class="panel twofa-panel"><span class="security-icon"><i class="bi bi-shield-lock"></i></span><h3>Autenticação em dois fatores (2FA)</h3><p class="help">Protege o painel mesmo que a senha seja descoberta. Use Google Authenticator, Microsoft Authenticator ou aplicação TOTP compatível.</p><div class="twofa-state ${twofa.enabled?'on':'off'}"><i class="bi ${twofa.enabled?'bi-check-circle-fill':'bi-exclamation-circle'}"></i> ${twofa.enabled?'Ativada':'Desativada'}</div>${twofa.enabled?`<form id="disable2faForm" class="stack"><input type="password" name="password" placeholder="Senha do administrador" required><input name="token" inputmode="numeric" maxlength="6" placeholder="Código de 6 dígitos" required><button class="danger">Desativar 2FA</button></form>`:`<button id="setup2faBtn">Configurar 2FA</button><div id="twofaSetup" class="twofa-setup" hidden></div>`}</div>
  </div>
  <div class="panel"><div class="admin-section-head"><div><h3>Privacidade dos documentos de identidade</h3><p class="help">Documentos validados são eliminados automaticamente após o período de retenção configurado no servidor.</p></div><button class="secondary" id="purgeIdentities"><i class="bi bi-trash3"></i> Executar limpeza agora</button></div></div>
  <div class="panel"><h3>Pedidos de recuperação de profissionais</h3><p class="help">Valide o pedido antes de gerar uma senha temporária e envie-a apenas ao contacto registado.</p><div class="reset-list">${requests.map(r=>`<article><div><b>${esc(r.professional_profiles?.name||r.email)}</b><p>${esc(r.email)} • ${esc(r.whatsapp)}</p><small>${esc(r.status)} • ${new Date(r.created_at).toLocaleString('pt-PT')}</small></div>${r.status==='pending'?`<div><button data-reset-action="resolve" data-reset-id="${esc(r.id)}">Gerar senha temporária</button><button class="danger" data-reset-action="reject" data-reset-id="${esc(r.id)}">Rejeitar</button></div>`:''}</article>`).join('')||'<p>Nenhum pedido.</p>'}</div></div>
  <div class="panel recovery-info"><h3><i class="bi bi-life-preserver"></i> Recuperação do administrador</h3><p>A recuperação de emergência continua protegida pela <b>ADMIN_RECOVERY_KEY</b> configurada no ambiente do Render. Nunca partilhe essa chave.</p></div>`;
  $('#passwordForm').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,v=Object.fromEntries(new FormData(form));if(v.newPassword!==v.confirmPassword)return alert('As duas novas senhas não coincidem.');try{await api('/api/admin/change-password',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({currentPassword:v.currentPassword,newPassword:v.newPassword})});form.reset();alert('Senha alterada com sucesso.')}catch(err){alert(err.message)}};
  $('#purgeIdentities').onclick=async()=>{if(!await uiConfirm('Executar agora a limpeza de documentos cujo prazo de retenção expirou?',{title:'Limpeza de documentos',confirmText:'Executar limpeza'}))return;try{await api('/api/admin/purge-expired-identities',{method:'POST'});alert('Limpeza concluída.');renderModeration()}catch(e){alert(e.message)}};
  $$('[data-reset-action]',box).forEach(btn=>btn.onclick=()=>btn.dataset.resetAction==='resolve'?window.resolveReset(btn.dataset.resetId):window.rejectReset(btn.dataset.resetId));
  if(twofa.enabled){$('#disable2faForm').onsubmit=async e=>{e.preventDefault();if(!await uiConfirm('Desativar a autenticação em dois fatores?',{title:'Desativar 2FA',danger:true}))return;try{await api('/api/admin/2fa/disable',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))});renderSecurity()}catch(err){alert(err.message)}}}
  else if($('#setup2faBtn')){$('#setup2faBtn').onclick=async()=>{try{const x=await api('/api/admin/2fa/setup',{method:'POST'});const target=$('#twofaSetup');target.hidden=false;target.innerHTML=`<div class="twofa-secret"><small>Chave para o autenticador</small><code>${esc(x.secret)}</code><p>Adicione manualmente esta chave numa aplicação autenticadora. Depois digite o código de 6 dígitos abaixo.</p></div><form id="enable2faForm" class="stack"><input name="token" inputmode="numeric" maxlength="6" placeholder="Código de 6 dígitos" required><button>Confirmar e ativar 2FA</button></form>`;$('#enable2faForm').onsubmit=async ev=>{ev.preventDefault();try{await api('/api/admin/2fa/enable',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(ev.currentTarget)))});alert('2FA ativada. No próximo login será solicitado um código.');renderSecurity()}catch(err){alert(err.message)}}}catch(err){alert(err.message)}}}
}
window.resolveReset=async id=>{try{const x=await api(`/api/admin/password-reset-requests/${id}/reset`,{method:'POST'});await uiPrompt(`Senha temporária de ${x.name}. Copie este código e envie apenas ao contacto registado.`,{title:'Senha temporária gerada',defaultValue:x.temporaryPassword,multiline:false,confirmText:'Fechar'});renderSecurity()}catch(e){alert(e.message)}};window.rejectReset=async id=>{if(!await uiConfirm('Rejeitar este pedido de recuperação?',{title:'Rejeitar recuperação',danger:true}))return;try{await api(`/api/admin/password-reset-requests/${id}/reject`,{method:'POST'});renderSecurity()}catch(e){alert(e.message)}};
init();
